### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by devmsh** [lucid-architecture/laravel-microservice#7]
Any plans to support 5.7? or the project no longer supported?

**Comment by harris21** [comment]
We’ll try supporting Laravel v5.7 as soon as we have some spare time. Meanwhile, PRs are always welcome :)

**Comment by devmsh** [comment]
@harris21 I'm really interested to contribute on that, but it seems that no updates going on here? unless laravel version support? 

Do you still use it internally? and it's production proven?

**Comment by harris21** [comment]
@devmsh What kind of updates would you like to see? Some suggestions would really help!

The project is stable and production ready, so we only do Laravel version updates at the moment. Yes, we still use it for all our Laravel related services (30+ services running on production currently).

**Comment by devmsh** [comment]
Cool

We decided to use it in our next project, and we will submit PR once we have the 5.7 upgrade done.
