### ISSUE TITLE
I can't find where to register services

### ISSUE THREAD

**Issue by mbengchan** [lucid-architecture/laravel-microservice#9]
Hey guys, thanks very much for this awesome architecture. from the video i watched on youtube the architecture seems interesting and i want to implement it on the project am working but when i create a service can find a place to register it. 

the ServiceProvider in Foundation folder is not found. Please i need your assistance. Even the migrations that i create in the service when i ran php artisan migrate they do not migrate.

Please for your help

**Comment by harris21** [comment]
Hello @Shadomax and welcome.
I believe you are looking at the wrong project. If you wish to create and use different services under the same codebase, you should take a look at https://github.com/lucid-architecture/laravel
The lucid-microservice project you are using should only be used as a standalone (micro)service.
You can also check the documentation for further clarification.
